version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: 
    - '5432:${DB_PORT}'
    networks:
    - local-network
  
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      REDIS_URL: ${REDIS_URL}:${REDIS_PORT}
    ports:
    - '6379:${REDIS_PORT}'
    networks:
    - local-network

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
    - '5672:${RABBITMQ_PORT}'
    networks:
    - local-network

networks:
  local-network:
    driver: bridge


