version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: nodejs-db
    ports: 
    - '5432:5432'
    networks:
    - local-network
  
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      REDIS_URL: redis://localhosst
    ports:
    - '6379:6379'
    networks:
    - local-network

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
    - '5672:5672'
    networks:
    - local-network

networks:
  local-network:
    driver: bridge


